name: flutter_qjs_example
description: Demonstrates how to use the flutter_qjs plugin.
publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_qjs:
    path: ../


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

